import {
  DetailsWrapper,
  Details,
  DetailsHeading,
  DetailsDescription,
  PhoneWrapper,
  Phone,
  PhoneNotch,
  PhoneProfileWrapper,
  PhoneProfile,
  PhoneProfileName,
  PhoneProfileImage,
  PhoneProfileText,
  PhoneProfileIconBack,
  PhoneProfileIconMenu,
  PhoneChatArea,
  PhoneChatBubble,
  PhoneChatImage,
  PhoneChatPricingBubble,
  PhoneSubmitButton,
  PhoneSubmitButtonIcon,
  PhoneChatTextInput,
  HeroBlob,
} from "./chat-app_styles.js";
